<?php 
/**
 * View -- of Administration/MasterController/editblock
 * chophel@athang.com
 */
$this->headTitle($this->title);
?>
<?php foreach($blocks as $row);?>
<form id="#form" method="post" action="<?php echo $this->url('setmaster', array('action' => 'editblock','id'=>$page)); ?>"  enctype="multipart/form-data" >                  
	<div class="modal-header">
		<h4 class="modal-title"> <i class="icon ti ti-edit"></i> <?php echo $this->title; ?></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">   
		<div class="row">
			<input type="hidden" id="block_id" name="block_id" value="<?php echo $row['id'];?>" />
			<div class="form-group mb-3">  
				<label class="form-label" for="DzongkhagId">Dzongkhag</label>
				<select id="DzongkhagId" name="DzongkhagId" class="form-select" data-placeholder="Select">
					<?php foreach($districts as $district):?>
						<option value="<?php echo $district['id']?>" <?php echo ($row['DzongkhagId']==$district['id'])?'selected':'';?>>
							<?php echo $district['DzongkhagNameEn'];?></option>
					<?php endforeach;?>
				</select>
			</div>
			<div class="form-group mb-3"> 
				<label class="form-label" for="GewogNameEn">Gewog Name En</label>
				<input type="text" class="form-control" value="<?php echo $row['GewogNameEn'];?>" name="GewogNameEn" id="GewogNameEn" placeholder="Gewog Name En" required /> 
			</div>
			<div class="form-group mb-3"> 
				<label class="form-label" for="GewogNameDz">Gewog Name Dz</label>
				<input type="text" class="form-control" value="<?php echo $row['GewogNameDz'];?>" name="GewogNameDz" id="GewogNameDz" placeholder="Gewog Name Dz" required /> 
			</div>
			<div  class="form-group mb-3">
				<label for="status" class="form-label">Status</label>
				<div>
					<label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="1" <?php echo ($row['status']=='1')?"checked":"";?> />
						<span class="form-check-label"> Yes </span>
					</label>
					<label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="0" <?php echo ($row['status']=='0')?"checked":"";?> />
						<span class="form-check-label"> No </span>
					</label>
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="icon ti ti-check"></i>Save</button>
		<button type="button" class="btn btn-warning" data-bs-dismiss="modal"><i class="icon ti ti-x"></i>Cancel</button> 
    </div>
</form>
<script>
$(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			DzongkhagId: {
				validators: {
					notEmpty: {
						message: 'Please select Dzongkhag.'
					}
				}
			},
			GewogNameEn: {
				validators: {
					notEmpty: {
						message: 'Please provide Gewog Name En.'
					}
				}
			},
			GewogNameDz: {
				validators: {
					notEmpty: {
						message: 'Please provide Gewog Name Dz.'
					}
				}
			},
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap5: new FormValidation.plugins.Bootstrap5({
				rowSelector: '.mb-3',
			}),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>