 <?php
/**
 * View -- of Administration/MasterController/editlocationtypeAction
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<?php foreach ($locationtypes as $row);?> 
<form id="#form" action="<?php echo $this->url('setmaster', array('action' => 'editlocationtype', 'id' => $page));?>" method="post" enctype="multipart/form-data">
	<div class="modal-header">
		<h4 class="modal-title"> <i class="icon ti ti-edit"></i> <?php echo $this->title; ?></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div> <!-- /modal-header -->
    <div class="modal-body">
		<div class="row"> 
			<input type="hidden" id="locationtype_id" name="locationtype_id" value="<?php echo $row['id'];?>" />
			<div  class="form-group mb-3">
				<label for="location_type" class="form-label">Location Type</label>
				<input class="form-control" value="<?php echo $row['location_type'];?>" type="text" name="location_type" id="location_type" placeholder="Location Type" required />
			</div>
			<div  class="form-group mb-3">
				<label for="description" class="form-label">Description</label>
				<input class="form-control" value="<?php echo $row['description'];?>" type="text" name="description" id="description" placeholder="Description" required />
			</div>
			<div  class="form-group mb-3">
				<label for="status" class="form-label">Status</label>
				<div>
					<label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="1" <?php echo ($row['status']=='1')?"checked":"";?> />
						<span class="form-check-label"> Yes </span>
					</label>
					<label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="0" <?php echo ($row['status']=='0')?"checked":"";?> />
						<span class="form-check-label"> No </span>
					</label>
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="icon ti ti-check"></i>Save</button>
		<button type="button" class="btn btn-warning" data-bs-dismiss="modal"><i class="icon ti ti-x"></i>Cancel</button> 
    </div>  
</form>
<script>
$(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			location_type: {
				validators: {
					notEmpty: {
						message: 'Please provide Location type.'
					}
				}
			},
			description: {
				validators: {
					notEmpty: {
						message: 'Please provide description.'
					}
				}
			},
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap5: new FormValidation.plugins.Bootstrap5({
				rowSelector: '.mb-3',
			}),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>