<?php
/**
 * Layout --- Bottom Navbar
 * chophel@athang.com
 */
 $user = $this->identity();
?>
<?php if($this->identity()): ?>
<?php endif; ?>
<footer class="footer footer-transparent d-print-none">
	<div class="container-xl">
		<div class="row text-center align-items-center flex-row-reverse">
			<div class="col-lg-auto ms-lg-auto">
				<ul class="list-inline list-inline-dots mb-0">
					<li class="list-inline-item"><a href="<?php echo $this->url('application',array('action'=>'documentation'));?>" class="link-secondary">Documentation</a></li>
				</ul>
			</div>
			<div class="col-12 col-lg-auto mt-3 mt-lg-0">
				<ul class="list-inline list-inline-dots mb-0">
					<li class="list-inline-item">
						Copyright &copy; 2021-<?php echo date('Y');?>
						<a href="https://www.doc.gov.bt/" target="_blank" class="link-secondary">Nangten-DoC Dept.ofCulture-MoHCA</a>.
						All rights reserved.
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer>