<?php 
/**
 * View -- of Nangten/MasterController/editsubcategory
 * chophel@athang.com
 */
$this->headTitle($this->title);
?>
<?php foreach($subcategory as $row);?>
<form id="#form" method="post" action="<?php echo $this->url('ngmaster', array('action' => 'editsubcategory','id'=>$page)); ?>" enctype="multipart/form-data">                  
    <div class="modal-header">
        <h4 class="modal-title"> <i class="icon ti ti-circle-plus"></i><?php echo $this->title; ?></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">   
		<div class="row">
        <input type="hidden" name="subcategory_id" value="<?php echo $row['id'];?>">
            <div class="form-group mb-3">
				<label for="sub_category" class="form-label">Sub-category</label>
				<input type="text" class="form-control" name="sub_category" id="sub_category" value="<?php echo $row['sub_category'];?>" placeholder="Sub-category" required />
            </div>
            <div class="form-group mb-3">
                <label for="group" class="form-label">Group</label>
                <select id="group" name="group" class="form-select" data-placeholder="Select">
					<option value=""></option>
					<?php foreach($group as $groups):?>
						<option value="<?php echo $groups['id']?>" <?php echo ($row['group']==$groups['id'])?'selected':'';?>>
							<?php echo $groups['GroupNameEn'];?></option>
					<?php endforeach;?>
				</select>
            </div>
            <div class="form-group mb-3">
                <label for="category" class="form-label">Category</label>
                <select id="category" name="category" class="form-select" data-placeholder="Select">
					<option value=""></option>
					<?php foreach($category as $categorys):?>
						<option value="<?php echo $categorys['id']?>" <?php echo ($row['category']==$categorys['id'])?'selected':'';?>>
							<?php echo $categorys['category'];?></option>
					<?php endforeach;?>
				</select>
            </div>
            <div  class="mb-3 col-lg-4">
				<label for="status" class="form-label">Status</label>
				<div class="mb-3">
                    <label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="1" <?php echo ($row['status']=='1')?"checked":"";?> />
						<span class="form-check-label"> Yes </span>
					</label>
					<label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="0" <?php echo ($row['status']=='0')?"checked":"";?> />
						<span class="form-check-label"> No </span>
					</label>
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="icon ti ti-check"></i>Save</button>
        <button type="button" class="btn btn-warning" data-bs-dismiss="modal"><i class="icon ti ti-x"></i>Cancel</button> 
    </div>
</form>
<script>
$(function(){
    $('select#group').on('change', function(){
	$.post(
		 "<?php echo $this->url("ngmaster", array("action" => "getcategory")); ?>",
            {
                groupId: $(this).val(),
            },
            function(data){
                $("select#category").html(data.categoryValue);
                $('select#category').trigger('chosen:updated');
            },
            'json'
        );
    });
   const fv = FormValidation.formValidation(document.getElementById('#form'), {
           fields: {
            category: {
                validators: {
                    notEmpty: {
                        message: 'Please provide category.'
                    }
                }
            },
            group: {
                validators: {
                    notEmpty: {
                        message: 'Please select group.'
                    }
                }
            },
            sub_category: {
                validators: {
                    notEmpty: {
                        message: 'Please select sub category.'
                    }
                }
            },
            status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
        },
        plugins: {
            trigger: new FormValidation.plugins.Trigger(),
            bootstrap5: new FormValidation.plugins.Bootstrap5({
                rowSelector: '.mb-3',
            }),
            submitButton: new FormValidation.plugins.SubmitButton(),
            defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
        },
    }).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>