<?php 
/**
 * View -- of Nangten/MasterController/editcategory
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<?php foreach($this->categoryObj->get($category_id) as $row);?>
<form id="#form" method="post" action="<?php echo $this->url('ngmaster', array('action' => 'editcategory','id'=>$page)); ?>"  enctype="multipart/form-data" >                  
    <div class="modal-header">
		<h4 class="modal-title"> <i class="icon ti ti-circle-plus"></i><?php echo $this->title; ?></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">   
		<div class="row">
		   <input type="hidden" name="category_id" value="<?php echo $row['id'];?>">
		   <div class="form-group mb-3">
				<label class="form-label" for="category">Category</label>
				<input type="text" class="form-control" name="category" id="category" value="<?php echo $row['category'];?>" placeholder="Category" required /> 
			</div>
			<div class="form-group mb-3">
				<label class="form-label" for="group">Group</label>
				<select id="group" name="group" class="form-select" data-placeholder="Select">
					<option value=""></option>
					<?php foreach($group as $groups):?>
						<option value="<?php echo $groups['id']?>" <?php echo ($row['group']==$groups['id'])?'selected':'';?>>
							<?php echo $groups['GroupNameDz'];?></option>
					<?php endforeach;?>
				</select>
			</div>
			<div class="row">
            <div  class="mb-3 col-lg-4">
				<label for="status" class="form-label">Status</label>
				<div class="mb-3">
                    <label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="1" <?php echo ($row['status']=='1')?"checked":"";?> />
						<span class="form-check-label"> Yes </span>
					</label>
					<label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="0" <?php echo ($row['status']=='0')?"checked":"";?> />
						<span class="form-check-label"> No </span>
					</label>
				</div>
			</div>
        </div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="icon ti ti-check"></i>Save</button>
        <button type="button" class="btn btn-warning" data-bs-dismiss="modal"><i class="icon ti ti-x"></i>Cancel</button> 
    </div>
</form>
<script>
$(function(){
    const fv = FormValidation.formValidation(document.getElementById('#form'), {
        fields: {
			category: {
                validators: {
                    notEmpty: {
                        message: 'Please select Category.'
                    }
                }
            },
        },
        plugins: {
            trigger: new FormValidation.plugins.Trigger(),
            bootstrap5: new FormValidation.plugins.Bootstrap5({
                rowSelector: '.mb-3',
            }),
            submitButton: new FormValidation.plugins.SubmitButton(),
            defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
        },
    }).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>