<?php 
/**
 * View -- of Nangten/ThankaController/thankaAction
 * chophel@athang.com 
 */
	$this->headTitle($this->title);
?>
<?php foreach($thanka as $thankas);?>
<div class="page-body">
	<div class="container-xl">
		<div class="row row-cards">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title"><i class="icon ti ti-user-plus"></i><?php echo $this->title;?></h3>
					</div>
					<form id="#form" method="post" action="<?php echo $this->url('thanka', array('action' => 'editthanka','id'=>$thankas['id'])); ?>" enctype="multipart/form-data" >
					<input type="hidden" name="thanka_id" value=<?php echo $thankas['id'];?>>
					<div class="card-body">
						<h4 class="fs-2"><strong><i>དབྱེ་ཁག།</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
						 <div class="row">
							<div class="form-group mb-3 col-lg-6">
									<label for="category" class="form-label">དྲོན་སོ།</label>
									<div class="input-group mb-2">
										<select id="category" name="category" class="form-select" data-placeholder="Select">
											<?php foreach($category as $categorys):?>
												<option value="<?php echo $categorys['id']?>" <?php echo ($thankas['category']==$categorys['id'])?'selected':'';?>> 
													<?php echo $categorys['category'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
								<div class="form-group mb-3 col-lg-6">
									<label for="subcategory" class="form-label">དཀོན་གཉེར་གྱི་མིང་རྟགས།</label>
									<div class="input-group mb-2">
										<select id="subcategory" name="subcategory" class="form-select" data-placeholder="Select">
											<?php foreach($subcategory as $subcategorys):?>
												<option value="<?php echo $subcategorys['id']?>" <?php echo ($thankas['subcategory']==$subcategorys['id'])?'selected':'';?>> 
													<?php echo $subcategorys['sub_category'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
							</div>
							<h4 class="fs-2"><strong><i>ལྷ་ཁང་ཁ་གསལ།</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label for="DzongkhagId" class="form-label">རྫོང་ཁག་</label>
									<div class="input-group mb-2">
										<select id="DzongkhagId" name="DzongkhagId" class="form-select" data-placeholder="Select">
											<?php foreach($dzongkahg as $dzongkhags):?>
												<option value="<?php echo $dzongkhags['old_id']?>" <?php echo ($thankas['DzongkhagId']==$dzongkhags['old_id'])?'selected':'';?>> 
													<?php echo $dzongkhags['DzongkhagNameDz'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="dob" class="form-label">རྒེད་འོག་:</label>
										<select id="GewogId" name="GewogId" class="form-select" data-placeholder="Select">
											<?php foreach($gewog as $gewogs):?>
												<option value="<?php echo $gewogs['id']?>" <?php echo ($thankas['GewogId']==$gewogs['id'])?'selected':'';?>> 
													<?php echo $gewogs['GewogNameDz'];?></option>
											<?php endforeach;?>
										</select>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="name" class="form-label">གཡུས་</label>
									<select id="VillageId" name="VillageId" class="form-select" data-placeholder="Select">
										<?php foreach($village as $villages):?>
											<option value="<?php echo $villages['id']?>" <?php echo ($thankas['VillageId']==$villages['id'])?'selected':'';?>> 
												<?php echo $villages['VillageNameDz'];?></option>
										<?php endforeach;?>
									</select>
								</div>
							</div>
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label for="LhakhangId" class="form-label">ལྷ་ཁང་གི་མིང་</label>
									<select id="LhakhangId" name="LhakhangId" class="form-select" data-placeholder="Select">
										<?php foreach($lhakhang as $lhakhangs):?>
											<option value="<?php echo $lhakhangs['id']?>" <?php echo ($thankas['LhakhangId']==$lhakhangs['id'])?'selected':'';?>> 
												<?php echo $lhakhangs['LhakhangNameDz'];?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="mobile" class="form-label">ནང་གསེས་</label>
									<select id="LhaSectionId" name="LhaSectionId" class="form-select" data-placeholder="Select">
										<?php foreach($section as $sections):?>
											<option value="<?php echo $sections['id']?>" <?php echo ($thankas['LhakhangId']==$sections['id'])?'selected':'';?>> 
												<?php echo $sections['SectionNameDz'];?></option>
										<?php endforeach;?>
									</select>
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaBuilderDz" class="form-label">བཞེངས་མི།</label>
									<input type="text" class="form-control" placeholder="བཞེངས་མི།." name="LhaBuilderDz" value="<?php echo $thankas['LhaBuilderDz'];?>" autocomplete="off" required >	
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaCenturyDz" class="form-label">དུས་རབས།</label>
									<input type="text" class="form-control" placeholder="དུས་རབས།" name="LhaCenturyDz" value="<?php echo $thankas['LhaCenturyDz'];?>" autocomplete="off" required >	
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaOwnerNameDz" class="form-label">དབྱེ་བ་གཞན།</label>
									<input type="text" class="form-control" placeholder="དབྱེ་བ་གཞན།" name="LhaOwnerNameDz" value="<?php echo $thankas['LhaOwnerNameDz'];?>" autocomplete="off" required >	
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaIdentificationNumber" class="form-label">དགུང་ཨང།</label>
									<input type="text" class="form-control" placeholder="དགུང་ཨང།" name="LhaIdentificationNumber" value="<?php echo $thankas['LhaIdentificationNumber'];?>" autocomplete="off" required >	
								</div>		
							</div>
							<h4 class="fs-2"><strong><i>ནང་རྟེན་ཁ་གསལ།</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="role">མཚན་གསལ།</label>
									<input type="text" class="form-control" placeholder="མཚན་གསལ།" name="TenDescriptionDz" value="<?php echo $thankas['TenDescriptionDz'];?>" autocomplete="off" required >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenNoofDeitiesDz">ལྷ་ཚོགས་གྲངས།</label>
									<input type="text" class="form-control" placeholder="ལྷ་ཚོགས་གྲངས།" name="TenNoofDeitiesDz" value="<?php echo $thankas['TenNoofDeitiesDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenGoldScriptDz" class="form-label">གསེར་བྲིས།</label>
									<input type="text" class="form-control" placeholder="གསེར་བྲིས།" name="TenGoldScriptDz" value="<?php echo $thankas['TenGoldScriptDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenTypeDz">བཟོ་བསྐྲུན།</label>
									<input type="text" class="form-control" placeholder="བཟོ་བསྐྲུན།" name="TenTypeDz" value="<?php echo $thankas['TenTypeDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenSideMatDz" class="form-label">མཐའ་འཇའ།</label>
									<input type="text" class="form-control" placeholder="མཐའ་འཇའ།" name="TenSideMatDz" value="<?php echo $thankas['TenSideMatDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenBotmMatDz">མཐོངས།</label>
									<input type="text" class="form-control" placeholder="མཐོངས།" name="TenBotmMatDz" value="<?php echo $thankas['TenBotmMatDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCoverDz">ཞལ་ཁེབས།</label>
									<input type="text" class="form-control" placeholder="ཞལ་ཁེབས།" name="TenCoverDz" value="<?php echo $thankas['TenCoverDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenStickBotmDz" class="form-label">ཏོག་</label>
									<input type="text" class="form-control" placeholder="Stick Bottom" name="TenStickBotmDz" value="<?php echo $thankas['TenStickBotmDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenHolderDz">སྲིང་ཅུང།</label>
									<input type="text" class="form-control" placeholder="སྲིང་ཅུང།" name="TenHolderDz" value="<?php echo $thankas['TenHolderDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenBuilderDz" class="form-label">བཞེངས་མི།</label>
									<input type="text" class="form-control" placeholder="བཞེངས་མི།" name="TenBuilderDz" value="<?php echo $thankas['TenBuilderDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenBackingDz">རྒྱབ་ཤབ།</label>
									<input type="text" class="form-control" placeholder="རྒྱབ་ཤབ།" name="TenBackingDz" value="<?php echo $thankas['TenBackingDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenSourceDz">འབྱུང་ཁུངས།</label>
									<input type="text" class="form-control" placeholder="འབྱུང་ཁུངས།" name="TenSourceDz" value="<?php echo $thankas['TenSourceDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenAreaBoarderDz">མཐའ་འཇའ་སྤྲགས་ཚད།</label>
									<input type="text" class="form-control" placeholder="མཐའ་འཇའ་སྤྲགས་ཚད།" name="TenAreaBoarderDz" value="<?php echo $thankas['TenAreaBoarderDz'];?>" autocomplete="off"  >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenMeasurePaintedArDz">མེ་ལོ་ཚད།</label>
									<input type="text" class="form-control" placeholder="མེ་ལོ་ཚད།" name="TenMeasurePaintedArDz" value="<?php echo $thankas['TenMeasurePaintedArDz'];?>" autocomplete="off"  >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCostDz">གོང་ཚད།</label>
									<input type="text" class="form-control" placeholder="གོང་ཚད།" name="TenCostDz" value="<?php echo $thankas['TenCostDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenQtyDz">གྲངས་ཁ།</label>
									<input type="text" class="form-control" placeholder="གྲངས་ཁ།" name="TenQtyDz" value="<?php echo $thankas['TenQtyDz'];?>" autocomplete="off"  >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenConditionDz" class="form-label">ཉམས་སྐྱོན།</label>
									<input type="text" class="form-control" placeholder="ཉམས་སྐྱོན།" name="TenConditionDz" value="<?php echo $thankas['TenConditionDz'];?>" autocomplete="off"  >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCaseDz">ཐང་ཤུབས།</label>
									<input type="text" class="form-control" placeholder="ཐང་ཤུབས།" name="TenCaseDz" value="<?php echo $thankas['TenCaseDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenColorDz">ཚོན་གྱི་དབྱེ་བ།</label>
									<input type="text" class="form-control" placeholder="ཚོན་གྱི་དབྱེ་བ།" name="TenColorDz" value="<?php echo $thankas['TenColorDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenIdentificationDz">ངོས་འཛིན།</label>
									<input type="text" class="form-control" placeholder="ངོས་འཛིན་།" name="TenIdentificationDz" value="<?php echo $thankas['TenIdentificationDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenStoryDz">ལོ་རྒྱུས།</label>
									<input type="text" class="form-control" placeholder="ལོ་རྒྱུས།" name="TenStoryDz" value="<?php echo $thankas['TenMeasurePaintedArDz'];?>" autocomplete="off" >
								</div>
							</div>
							<h4 class="fs-2"><strong><i>དྲན་གསཽ།</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCaretakerDz">དཀོན་གཉེར་གྱི་མིང་རྟགས།</label>
									<input type="text" class="form-control" placeholder="དཀོན་གཉེར་གྱི་མིང་རྟགས།" name="TenCaretakerDz"value="<?php echo $thankas['TenCaretakerDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCheckedByDz">ཞིབ་དཔྱོད་པའི་མིང་རྟགས།</label>
									<input type="text" class="form-control" placeholder="ཞིབ་དཔྱོད་པའི་མིང་རྟགས།" name="TenCheckedByDz" value="<?php echo $thankas['TenCheckedByDz'];?>" autocomplete="off" >
								</div>
							</div>
						</div>
						<div class="card-footer">
							<button type="submit" class="btn btn-success"><span class="icon ti ti-check"></span> Save</button>
							<a class="btn btn-warning" onclick="javascript:history.back();"><span class="icon ti ti-x"></span> Cancel </a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function(){
	$('select#category').on('change', function(){
	$.post(
		 "<?php echo $this->url("statue", array("action" => "getsubcategory")); ?>",
            {
                categoryId: $(this).val(),
            },
            function(data){
                $("select#subcategory").html(data.subcategoryValue);
                $('select#subcategory').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#DzongkhagId').on('change', function(){
	$.post(
		 "<?php echo $this->url("statue", array("action" => "getgewog")); ?>",
            {
                dzongkhagId: $(this).val(),
            },
            function(data){
                $("select#GewogId").html(data.gewogValue);
                $('select#GewogId').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#GewogId').on('change', function(){
	$.post(
		 "<?php echo $this->url("statue", array("action" => "getvillage")); ?>",
            {
                gewogId: $(this).val(),
            },
            function(data){
                $("select#VillageId").html(data.villageValue);
                $('select#VillageId').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#GewogId').on('change', function(){
	$.post(
		 "<?php echo $this->url("statue", array("action" => "getvillage")); ?>",
            {
                gewogId: $(this).val(),
            },
            function(data){
                $("select#VillageId").html(data.villageValue);
                $('select#VillageId').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#GewogId').on('change', function(){
	$.post(
		 "<?php echo $this->url("statue", array("action" => "getvillage")); ?>",
            {
                gewogId: $(this).val(),
            },
            function(data){
                $("select#LhakhangId").html(data.lhakhangValue);
                $('select#LhakhangId').trigger('chosen:updated');
            },
            'json'
        );
    });
	/*$('select#LhakhangId').on('change', function(){
	$.post(
		 "<?php //echo $this->url("nangten", array("action" => "getsection")); ?>",
            {
                lhaId: $(this).val(),
            },
            function(data){
                $("select#LhaSectionId").html(data.sectionValue);
                $('select#LhaSectionId').trigger('chosen:updated');
            },
            'json'
        );
    });*/
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				DzongkhagId: {
					validators: {
						notEmpty: {
							message: 'Please select dzongkhag.'
						},
					}
				},
				GewogId: {
					validators: {
						notEmpty: {
							message: 'Please select gewog.'
						},
					}
				},
				LhakhangId: {
					validators: {
						notEmpty: {
							message: 'Please select lhakhang.'
						},
					}
				},
				VillageId: {
					validators: {
						notEmpty: {
							message: 'Please select village'
						},
					}
				},
				LhaSectionId: {
					validators: {
						notEmpty: {
							message: 'Please select section.'
						}
					}
				},
				TenDescriptionDz: {
					validators: {
						notEmpty: {
							message: 'Please provide description.'
						}
					}
				},
				TenCaretakerDz: {
					validators: {
						notEmpty: {
							message: 'Please provide care taker.'
						}
					}
				},
				TenCheckedByDz: {
					validators: {
						notEmpty: {
							message: 'Please provide Checker.'
						}
					}
				},
				category: {
					validators: {
						notEmpty: {
							message: 'Please select category.'
						}
					}
				},
				subcategory: {
					validators: {
						notEmpty: {
							message: 'Please select Sub category.'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap5: new FormValidation.plugins.Bootstrap5({
					rowSelector: '.mb-3',
				}),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
		$('form select').chosen().change(function () {
			fv.revalidateField($(this).attr('name'));
		});
		picker.on('selected', function (e) {
			fv.revalidateField(picker.options.element.name);
		});
	});
</script>