<?php 
/**
 * View -- of Administration/UserController/useractivityAction
 * chophel@athang.com 
 */
	$this->headTitle($this->title);
?>
<?php foreach ($users as $user);?>
<div class="page-body">
	<div class="container-xl">
		<div class="row row-cards">
			<div class="col-12">
				<div class="card">
					<?php echo $this->tabs_helper(array(103,109,110),$user['id']); ?>
					<div class="card-header"></div>
					<div class="table-responsive">
						<table class="table card-table table-vcenter text-nowrap datatable" id="dataTables">
							<thead>
								<tr>
									<th>#</th>
									<th>Timestamp</th>
									<th>Process</th>
									<th>Status</th>
									<th>Remarks</th>          
								</tr>
							</thead>
							<tbody>
							<?php $i=1+(($page-1)*25); foreach($paginator as $row):?>
							<tr>
								<td><?php echo $i++; ?></td>
								<td><?php echo $row['created']; ?></td>
								<td><?php echo $this->processObj->getColumn($row['process'],'process'); ?></td>
								<td><?php echo $this->status($row['status']);?></td>
								<td><?php echo $row['remarks'];?></td>
							</tr>
							<?php endforeach;?>
							</tbody>
						</table>
					</div>
					<div class="card-footer d-flex align-items-center">
						<?php echo $this->paginationControl($this->paginator,'Sliding','adm_pagination.phtml', 
							array('route' => 'user/paginator','action'=>'useractivity','id'=>$user['id']));?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	var title_table = "<?php echo $this->title;?>";
	$('#dataTables').DataTable( {
		dom: 'Bfrtip',
		columnDefs: [ {
			visible: false
		} ],
		"paging":   false,
		"ordering": false,
		"info":     false,
		buttons: [
			{
				extend: 'copy',
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-copy"></i> Copy',
				titleAttr: 'Copy'
			},
			{
				extend: 'csv',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-file-text"></i> Csv',
				titleAttr: 'CSV'
			},
			{
				extend: 'excel',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-file-export"></i> Excel',
				titleAttr: 'Excel'
			},
			{
				extend: 'pdfHtml5',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				orientation: 'landscape',
				pageSize: 'LEGAL',
				text: '<i class="icon ti ti-file-invoice"></i> Pdf',
				titleAttr: 'PDF'
			},
			{
				extend: 'print',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-printer"></i> Print',
				titleAttr: 'Print'
			},	
		],
	});
</script>