<?php 
/**
 * View -- of Nangten/MasterController/addmaterialAction
 * chophel@athang.com
 */
$this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php echo $this->url('ngmaster', array('action' => 'addmaterial','id'=>$page)); ?>" enctype="multipart/form-data">                  
    <div class="modal-header">
        <h4 class="modal-title"> <i class="icon ti ti-circle-plus"></i><?php echo $this->title; ?></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">   
		<div class="row">
            <div class="form-group mb-3">
				<label for="MaterialNameDz" class="form-label">Material(Dzongkha)</label>
				<input type="text" class="form-control" name="MaterialNameDz" id="MaterialNameDz" placeholder="Material(Dzongkha)" required />
            </div>
            <div class="form-group mb-3">
				<label for="MaterialNameEn" class="form-label">Material(English)</label>
				<input type="text" class="form-control" name="MaterialNameEn" id="MaterialNameEn" placeholder="Material(English)" required />
            </div>
            <div class="form-group mb-3">
                <label for="group" class="form-label">Group</label>
                <select id="group" name="group" class="form-control" data-placeholder="Select" >
					<option value=""></option>
					<?php foreach($group as $groups):?>
						<option value="<?php echo $groups['id']?>">
							<?php echo $groups['GroupNameDz'];?></option>
					<?php endforeach;?>
				</select>
            </div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="icon ti ti-check"></i>Save</button>
        <button type="button" class="btn btn-warning" data-bs-dismiss="modal"><i class="icon ti ti-x"></i>Cancel</button> 
    </div>
</form>
<script>
$(function(){
    $('select#group').on('change', function(){
	$.post(
		 "<?php echo $this->url("ngmaster", array("action" => "getcategory")); ?>",
            {
                groupId: $(this).val(),
            },
            function(data){
                $("select#category").html(data.categoryValue);
                $('select#category').trigger('chosen:updated');
            },
            'json'
        );
    });
   const fv = FormValidation.formValidation(document.getElementById('#form'), {
           fields: {
            material: {
                validators: {
                    notEmpty: {
                        message: 'Please provide material.'
                    }
                }
            },
            group: {
                validators: {
                    notEmpty: {
                        message: 'Please select group.'
                    }
                }
            },
        },
        plugins: {
            trigger: new FormValidation.plugins.Trigger(),
            bootstrap5: new FormValidation.plugins.Bootstrap5({
                rowSelector: '.mb-3',
            }),
            submitButton: new FormValidation.plugins.SubmitButton(),
            defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
        },
    }).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>