<?php 
/**
 * View -- of Awpb/MasterController/componentAction
 * chophel@athang.com 
 */
	$this->headTitle($this->title);
?>
<div class="page-body">
	<div class="container-xl">
		<div class="row row-cards">
			<div class="col-12">
				<div class="card">
				<?php echo $this->tabs_helper(array(202,205,208,211)); ?>
					<div class="card-header">
						<div class="col-auto ms-auto d-print-none">
							<div class="btn-list">
							<?php echo $this->button(2);?>
							</div>
						</div>
					</div>
					<div class="table-responsive">
						<table class="table card-table table-vcenter text-nowrap datatable" id="dataTables">
							<thead>
								<tr>
									<th>#</th>
									<th>སྡེ།</th>
									<th>གནས་སྟངས།</th>
									<?php if($this->button(1)!=""):?>
										<th class="no-sort no-printpdf">ལས།</th>
									<?php endif;?>	
								</tr>
							</thead>
							<tbody>
							<?php $i=1+(($page-1)*20); foreach ($paginator as $row):?>
								<tr>
									<td><?php  echo $i++; ?></td>								       
									<td class="fs-2"><?php echo $row['GroupNameDz'];?></td>
									<td><?php echo $this->status($row['status']);?></td>
									<?php if($this->button(1)!=""):?>
										<td><?php echo $this->button(1, $row['id'].'_'.$page);?></td>
									<?php endif;?>
								</tr>
							<?php endforeach; ?>
							</tbody>
						</table>
					</div>
					<div class="card-footer d-flex align-items-center">
						<?php echo $this->paginationControl($this->paginator,'Sliding','search_pagination.phtml', 
							array('route' => 'ngmaster/paginator','action'=>'category','id'=>'0'));?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	var title_table = "<?php echo $this->title;?>";
	$('#dataTables').DataTable( {
		dom: 'Bfrtip',
		columnDefs: [ {
			visible: false
		} ],
		"paging":   false,
		"ordering": false,
		"info":     false,
		buttons: [
			{
				extend: 'copy',
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-copy"></i> Copy',
				titleAttr: 'Copy'
			},
			{
				extend: 'csv',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-file-text"></i> Csv',
				titleAttr: 'CSV'
			},
			{
				extend: 'excel',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-file-export"></i> Excel',
				titleAttr: 'Excel'
			},
			{
				extend: 'pdfHtml5',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				orientation: 'landscape',
				pageSize: 'LEGAL',
				text: '<i class="icon ti ti-file-invoice"></i> Pdf',
				titleAttr: 'PDF'
			},
			{
				extend: 'print',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-printer"></i> Print',
				titleAttr: 'Print'
			},	
		],
	});
});
</script>