<?php 
/**
 * View -- of Nangten/StupaController/addstupaAction
 * chophel@athang.com 
 */
	$this->headTitle($this->title);
?>
<div class="page-body">
	<div class="container-xl">
		<div class="row row-cards">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title"><i class="icon ti ti-user-plus"></i><?php echo $this->title;?></h3>
					</div>
					<form id="#form" method="post" action="<?php echo $this->url('stupa', array('action' =>'addstupa')); ?>" enctype="multipart/form-data" >
						<div class="card-body">
						<h4><strong><i>Categorization</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
						 <div class="row">
								<div class="form-group mb-3 col-lg-6">
									<label for="category" class="form-label">Category</label>
									<div class="input-group mb-2">
										<select id="category" name="category" class="form-control" data-placeholder="Select" >
											<option value=""></option>
											<?php foreach($category as $categorys):?>
												<option value="<?php echo $categorys['id']?>">
													<?php echo $categorys['category'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
								<div class="form-group mb-3 col-lg-6">
									<label for="subcategory" class="form-label">Sub Category</label>
									<div class="input-group mb-2">
										<select id="subcategory" name="subcategory" class="form-control" data-placeholder="Select" >
											<option value=""></option>
										</select>
									</div>
								</div>
							</div>
							<h4><strong><i>Lhakhang details</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label for="DzongkhagId" class="form-label">རྫོང་ཁག་</label>
									<div class="input-group mb-2">
										<select id="DzongkhagId" name="DzongkhagId" class="form-control" data-placeholder="Select" >
											<option value=""></option>
											<?php foreach($dzongkahg as $dzos):?>
												<option value="<?php echo $dzos['id']?>">
													<?php echo $dzos['DzongkhagNameDz'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="dob" class="form-label">རྒེད་འོག་:</label>
									<select id="GewogId" name="GewogId" class="form-control" data-placeholder="Select" >
											<option value=""></option>
									</select>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="name" class="form-label">གཡུས་</label>
									<select id="VillageId" name="VillageId" class="form-control" data-placeholder="Select" >
											<option value=""></option>
									</select>
								</div>
							</div>
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label for="email" class="form-label">ལྷ་ཁང་གི་མིང་</label>
									<select id="LhakhangId" name="LhakhangId" class="form-control" data-placeholder="Select" >
											<option value=""></option>
									</select>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="mobile" class="form-label">གསེས་</label>
									<select id="LhaSectionId" name="LhaSectionId" class="form-control" data-placeholder="Select" >
											<option value=""></option>
									</select>
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaBuilderDz" class="form-label">བཞེངས་མི</label>
									<input type="text" class="form-control" placeholder="LhaBuilderDz." name="LhaBuilderDz" value="" autocomplete="off" required >	
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaCenturyDz" class="form-label">དུས་རབས</label>
									<input type="text" class="form-control" placeholder="LhaCenturyDz." name="LhaCenturyDz" value="" autocomplete="off" required >	
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaOwnerNameDz" class="form-label">དབྱེ་བ་གཞན་</label>
									<input type="text" class="form-control" placeholder="LhaOwnerNameDz" name="LhaOwnerNameDz" value="" autocomplete="off" required >	
								</div>		
							</div>
							<h4><strong><i>Nangten Details</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
							    <div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="role">ལྷ་ཚོགས་</label>
									<input type="text" class="form-control" placeholder="TenDescriptionDz" name="TenDescriptionDz" value="" autocomplete="off" required >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenMakeId">རྒྱུ་</label>
									<select id="TenMakeId" name="TenMakeId" class="form-control" data-placeholder="Select" >
											<option value=""></option>
											<?php foreach($material as $materials):?>
												<option value="<?php echo $materials['id']?>">
													<?php echo $materials['MaterialNameDz'];?></option>
											<?php endforeach;?>
										</select>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenSizeDz">ཚད་</label>
									<input type="text" class="form-control" placeholder="Ten Size" name="TenSizeDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenShapeDz">གཤམ་ཚད་</label>
									<input type="text" class="form-control" placeholder="Ten Shape" name="TenShapeDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenWeightDz" class="form-label">ལྗིད་ཚད</label>
									<input type="text" class="form-control" placeholder="Ten Weight" name=" TenWeightDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenColorDz">མདོང་</label>
									<input type="text" class="form-control" placeholder="Ten Color" name="TenColorDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenSunDz" class="form-label">ཉི་མ་</label>
									<input type="text" class="form-control" placeholder="Ten Sun" name="TenSunDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenMoonDz">ཟླ་བ་</label>
									<input type="text" class="form-control" placeholder="Ten Moon" name="TenMoonDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenShadeDz">ཟར་ཚགས་</label>
									<input type="text" class="form-control" placeholder="Ten Shade" name="TenShadeDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenRingDz" class="form-label">འཁོར་ལོ་</label>
									<input type="text" class="form-control" placeholder="Ten Ring" name="TenRingDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenBumpaDz" class="form-label">བུམ་པ་</label>
									<input type="text" class="form-control" placeholder="Ten Bumpa" name="TenBumpaDz" value="" autocomplete="off" >
								</div>
								
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenWindowDz">སྒོ་ཁྱིམ་</label>
									<input type="text" class="form-control" placeholder="Ten Window" name="TenWindowDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenSertoDz">གསེར་སྒྲོན་</label>
									<input type="text" class="form-control" placeholder="Ten Serto" name="TenSertoDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenJwellWornDz">གཡུ་བྱུ་རུ་</label>
									<input type="text" class="form-control" placeholder="Ten Jwell worn" name="TenJwellWornDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenAgeDz">ལོ་ཚད་</label>
									<input type="text" class="form-control" placeholder="Ten Age" name="TenAgeDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenLifeImageDz">གཟུངས་གཞུག་སྐུ་</label>
									<input type="text" class="form-control" placeholder="Ten Life Image" name="TenLifeImageDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenMaterialHeightDz">རྒྱུ་ཚད་</label>
									<input type="text" class="form-control" placeholder="Ten Material Height" name="TenMaterialHeightDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenConditionDz">ཉམས་སྐྱོན་</label>
									<input type="text" class="form-control" placeholder="Condition" name="TenConditionDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenQtyDz">གྲངས་ཁ་</label>
									<input type="text" class="form-control" placeholder="Quantity" name="TenQtyDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenQualtyDz">ཚོན་གྱི་དབྱེ་་བ་</label>
									<input type="text" class="form-control" placeholder="Ten Qualty" name="TenQualtyDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenIdentificationDz">ངོས་འཛིན་</label>
									<input type="text" class="form-control" placeholder="Identification" name="TenIdentificationDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenStoryDz">ལོ་རྒྱུས་</label>
									<input type="text" class="form-control" placeholder="Story" name="TenStoryDz" value="" autocomplete="off" >
								</div>
							</div>
							<h4><strong><i>Other details</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCaretakerDz">དཀོན་གཉེར་གྱི་མིང་རྟགས།</label>
									<input type="text" class="form-control" placeholder="TenCaretakerDz" name="TenCaretakerDz" value="" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCheckedByDz">ཞིབ་དཔྱོད་པའི་མིང་རྟགས།</label>
									<input type="text" class="form-control" placeholder="TenCheckedByDz" name="TenCheckedByDz" value="" autocomplete="off" >
								</div>
							</div>
						</div>
						<div class="card-footer">
							<button type="submit" class="btn btn-success"><span class="icon ti ti-check"></span> Save</button>
							<a class="btn btn-warning" onclick="javascript:history.back();"><span class="icon ti ti-x"></span> Cancel </a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function(){
	$('select#category').on('change', function(){
	$.post(
		 "<?php echo $this->url("stupa", array("action" => "getsubcategory")); ?>",
            {
                categoryId: $(this).val(),
            },
            function(data){
                $("select#subcategory").html(data.subcategoryValue);
                $('select#subcategory').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#DzongkhagId').on('change', function(){
	$.post(
		 "<?php echo $this->url("stupa", array("action" => "getgewog")); ?>",
            {
                dzongkhagId: $(this).val(),
            },
            function(data){
                $("select#GewogId").html(data.gewogValue);
                $('select#GewogId').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#GewogId').on('change', function(){
	$.post(
		 "<?php echo $this->url("stupa", array("action" => "getvillage")); ?>",
            {
                gewogId: $(this).val(),
            },
            function(data){
                $("select#VillageId").html(data.villageValue);
                $('select#VillageId').trigger('chosen:updated');
				$("select#LhakhangId").html(data.lhakhangValue);
                $('select#LhakhangId').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#LhakhangId').on('change', function(){
	$.post(
		 "<?php echo $this->url("stupa", array("action" => "getsection")); ?>",
            {
                lhaId: $(this).val(),
            },
            function(data){
                $("select#LhaSectionId").html(data.sectionValue);
                $('select#LhaSectionId').trigger('chosen:updated');
            },
            'json'
        );
    });
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				DzongkhagId: {
					validators: {
						notEmpty: {
							message: 'Please select dzongkhag.'
						},
					}
				},
				GewogId: {
					validators: {
						notEmpty: {
							message: 'Please select gewog.'
						},
					}
				},
				LhakhangId: {
					validators: {
						notEmpty: {
							message: 'Please select lhakhang.'
						},
					}
				},
				VillageId: {
					validators: {
						notEmpty: {
							message: 'Please select village'
						},
					}
				},
				LhaSectionId: {
					validators: {
						notEmpty: {
							message: 'Please select section.'
						}
					}
				},
				TenMakeId: {
					validators: {
						notEmpty: {
							message: 'Please select Msterial.'
						}
					}
				},
				TenCaretakerDz: {
					validators: {
						notEmpty: {
							message: 'Please provide care taker.'
						}
					}
				},
				TenCheckedByDz: {
					validators: {
						notEmpty: {
							message: 'Please provide Checker.'
						}
					}
				},
				TenMakeId: {
					validators: {
						notEmpty: {
							message: 'Please select material.'
						}
					}
				},
				category: {
					validators: {
						notEmpty: {
							message: 'Please select category.'
						}
					}
				},
				subcategory: {
					validators: {
						notEmpty: {
							message: 'Please select Sub category.'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap5: new FormValidation.plugins.Bootstrap5({
					rowSelector: '.mb-3',
				}),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
		$('form select').chosen().change(function () {
			fv.revalidateField($(this).attr('name'));
		});
	});
</script>