<?php 
/**
 * View -- of Administration/MasterController/addlocation
 * chophel@athang.com
 */
$this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php echo $this->url('setmaster', array('action' => 'addlocation','id'=>$page)); ?>"  enctype="multipart/form-data" >                  
    <div class="modal-header">
		<h4 class="modal-title"> <i class="icon ti ti-circle-plus"></i> <?php echo $this->title; ?></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">   
		<div class="row">
			<div class="form-group mb-3 col-lg-6">  
				<label class="form-label" for="location_type">ས་གནས་དབྱེ་ཁག།</label>
				<select id="location_type" name="location_type" class="form-select" data-placeholder="Select">
					<option value=""></option>
					<?php foreach($locationtypes as $locationtype):?>
						<option value="<?php echo $locationtype['id']?>">
							<?php echo $locationtype['location_type'];?></option>
					<?php endforeach;?>
				</select>
			</div>
			<div class="form-group mb-3 col-lg-6">  
				<label class="form-label" for="district">རྫོང་ཁག།</label>
				<select id="district" name="district" class="form-control" data-placeholder="Select">
					<option value="-1" selected>None</option>
					<?php foreach($districts as $district):?>
						<option value="<?php echo $district['id']?>">
							<?php echo $district['DzongkhagNameDz'];?></option>
					<?php endforeach;?>
				</select>
			</div>
		</div>
		<div class="row">
			<div class="form-group mb-3 col-lg-12"> 
				<label class="form-label" for="location">ས་གནས།</label>
				<input type="text" class="form-control" name="location" id="location" placeholder="ས་གནས།" required /> 
			</div>
		</div>
		<div class="row">
			<div class="form-group mb-3 col-lg-6"> 
				<label class="form-label" for="coordinates">Coordinates</label>
				<input type="text" class="form-control" name="coordinates" id="coordinates" placeholder="Coordinates" /> 
			</div>
			<div  class="form-group mb-3 col-lg-6">
				<label for="status" class="form-label">གནས་སྟངས།</label>
				<div>
					<label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="1" checked />
						<span class="form-check-label">ཨྀན།</span>
					</label>
					<label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="0" />
						<span class="form-check-label">མཻན།</span>
					</label>
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="icon ti ti-check"></i>Save</button>
		<button type="button" class="btn btn-warning" data-bs-dismiss="modal"><i class="icon ti ti-x"></i>Cancel</button> 
    </div>
</form>
<script>
$(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			location: {
				validators: {
					notEmpty: {
						message: 'Please provide PIU name.'
					}
				}
			},
			location_type: {
				validators: {
					notEmpty: {
						message: 'Please select PIU type.'
					}
				}
			},
			district: {
				validators: {
					notEmpty: {
						message: 'Please select dzongkhag.'
					}
				}
			},
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap5: new FormValidation.plugins.Bootstrap5({
				rowSelector: '.mb-3',
			}),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>