<?php
/**
 * View -- of Administration/DomainController/locationAction
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<div class="page-body">
	<div class="container-xl">
		<div class="row row-cards">
			<div class="col-12">
				<div class="card">
					<?php echo $this->tabs_helper(array(117,120,123,126)); ?>
					<div class="card-header">
						<div class="col-9">
							<form method="POST">
								<div class="row">
									<div class="form-group mb-3 col-lg-6">
										<label for="location_type" class="form-label">ས་གནས་དབྱེ་ཁག།</label>
										<select id="location_type" name="location_type" class="form-select" data-placeholder="Select">
											<option value="-1" <?php echo ($locationtype_id == '-1')?'selected':'';?>>All</option>
											<?php foreach($this->locationtypeObj->get(array('status'=>'1')) as $locationtype):?>
												<option value="<?php echo $locationtype['id']?>"<?php echo ($locationtype['id']==$locationtype_id)?'selected':'';?>>
													<?php echo $locationtype['location_type'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
							</form>
						</div>
						<div class="col-auto ms-auto d-print-none">
							<div class="btn-list">
								<?php echo $this->button(2,$page);?>
							</div>
						</div>
					</div>
					<div class="table-responsive">
						<table class="table card-table table-vcenter text-nowrap datatable" id="dataTables">
							<thead>
								<tr>
									<th>#</th>
									<th>ས་གནས།</th>
									<th>ས་གནས་དབྱེ་ཁག།</th>
									<th>དབྱཻ་ཨང།</th>
									<th>རྫོང་ཁག།</th>
									<th>གནས་སྟངས།</th>
									<?php if($this->button(1)!=""):?>
										<th class="no-printpdf">ལས།</th>
									<?php endif;?>	
								</tr>
							</thead>
							<tbody>
							<?php 
								$i=1;
								foreach ($paginator as $row):?>
								<tr>
									<td><?php  echo $i++; ?></td>								       
									<td class="fw-bold"><?php echo $row['location']; ?></td>
									<td><?php echo $this->locationtypeObj->getColumn($row['location_type'],'location_type'); ?></td>
									<td><?php echo $row['location_code'];?></td>
									<td><?php echo ($row['district']!='-1')?$this->districtObj->getColumn($row['district'],'DzongkhagNameDz'):'-'; ?></td>
									<td><?php echo $this->status($row['status']); ?></td>
									<?php if($this->button(1)!=""):?>
										<td><?php echo $this->button(1, $row['id'].'_'.$page);?></td>
									<?php endif;?>
								</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
					</div>
					<div class="card-footer d-flex align-items-center">
						<?php echo $this->paginationControl($this->paginator,'Sliding','adm_pagination.phtml', 
							array('route' => 'setmaster/paginator','action'=>'location','id'=>'0'));?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	$('#location_type').change(function(){
		window.location.href="<?php echo $this->url('setmaster',array('action'=>'location'));?>/"+$(this).val();
	});
	var title_table = "<?php echo $this->title;?>";
	$('#dataTables').DataTable( {
		dom: 'Bfrtip',
		columnDefs: [ {
			visible: false
		} ],
		"paging":   false,
		"ordering": false,
		"info":     false,
		buttons: [
			{
				extend: 'copy',
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-copy"></i> Copy',
				titleAttr: 'Copy'
			},
			{
				extend: 'csv',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-file-text"></i> Csv',
				titleAttr: 'CSV'
			},
			{
				extend: 'excel',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-file-export"></i> Excel',
				titleAttr: 'Excel'
			},
			{
				extend: 'pdfHtml5',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				orientation: 'landscape',
				pageSize: 'LEGAL',
				text: '<i class="icon ti ti-file-invoice"></i> Pdf',
				titleAttr: 'PDF'
			},
			{
				extend: 'print',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="icon ti ti-printer"></i> Print',
				titleAttr: 'Print'
			},	
		],
	});
});
</script>