<?php 
/**
 * View -- of Administration/UserController/viewAction
 * chophel@athang.com 
 */
	$this->headTitle($this->title);
?>
<?php foreach($statue as $row);?>
<div class="page-body">
	<div class="container-xl">
		<div class="row row-cards">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<div class="col-2">
							<?php echo $this->button(3,$row['id']);?>
						</div>
						<div class="col-2">
							<?php echo $this->button(6,$row['id'],'','236');?>
						</div>
						<div class="col-2">
							<?php echo $this->button(6,$row['id'],'','235');?>
						</div>
					</div>
					<div class="row row-cards">
              			<div class="col-lg-4">
							<div class="card">
								<div class="card-body text-center">
									<div class="mb-3">
										<span class="avatar avatar-xl img-thumbnail" style="background-image: url(<?php echo $this->basePath()."/upload/statue/".$row['TenImage'];?>)"></span>
									</div>
								</div>
								<hr style="margin: 1rem 0;">
								<div class="card-header">
									<h3 class="card-title">Categorization</h3>
								</div>
								<div class="card-body">
									<dl class="row">
										<dt class="col-5">Category:</dt>
										<dd class="col-7"><?php echo $this->catObj->getColumn($row['category'],'category');?></dd>
										<dt class="col-5">Sub-Category:</dt>
										<dd class="col-7"><?php  echo $this->subcatObj->getColumn($row['subcategory'],'sub_category');?></dd>
									</dl>
								</div>
								<div class="card-header">
								<h3 class="card-title">Lhakhang Details</h3>
								</div>
								<div class="card-body">
									<dl class="row">
										<dt class="col-5 fs-2">རྫོང་ཁག་:</dt>
										<dd class="col-7 fs-2"><?php echo $row['DzongkhagNameDz'];?></dd>
										<dt class="col-5 fs-2">རྒེད་འོག་:</dt>
										<dd class="col-7 fs-2"><?php echo $row['GewogNameDz'];?></dd>
										<dt class="col-5 fs-2">གཡུས་:</dt>
										<dd class="col-7 fs-2"><?php echo $row['VillageDz'];?></dd>
										<dt class="col-5 fs-2">ལྷ་ཁང་གི་མིང་:</dt>
										<dd class="col-7 fs-2"><?php echo $row['LhakhangNameDz'];?></dd>
										<dt class="col-5 fs-2">གསེས་:</dt>
										<dd class="col-7 fs-2"><?php echo $row['LhaSectionNameDz'];?></dd>
										<dt class="col-5 fs-2">བཞེངས་མི:</dt>
										<dd class="col-7 fs-2"><?php echo $row['LhaBuilderDz'];?></dd>
										<dt class="col-5 fs-2">དུས་རབས:</dt>
										<dd class="col-7 fs-2"><?php echo $row['LhaCenturyDz'];?></dd>
										<dt class="col-5 fs-2">དབྱེ་བ་གཞན་:</dt>
										<dd class="col-7 fs-2"><?php echo $row['LhaOwnerNameDz'];?></dd>
									</dl>
								</div>
							</div>
						</div>
						<div class="col-lg-8">
							<div class="card">
								<div class="card-header">
									<h3 class="card-title">Nangten Details</h3>
								</div>
								<div class="card-body">
									<dl class="row">
										<dt class="col-5 fs-2">མཚན་གསལ:</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenDescriptionDz'];?></dd>
										<dt class="col-5 fs-2">རྒྱུ</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenMaterialDz'];?></dd>
										<dt class="col-5 fs-2">བཞུགས་ཚུལ་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenPostureDz'];?></dd>
										<dt class="col-5 fs-2">སྲོག་ཞུ་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenTreasureDz'];?></dd>
										<dt class="col-5 fs-2">བཛོད་སྤུར་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenForeHeadDz'];?></dd>
										<dt class="col-5 fs-2">ཕྱག་མཚན་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenForeHeadDz'];?></dd>
										<dt class="col-5 fs-2">ཞལ་དང་སྐུ་གཟུགས་ཀྱི་གསེར་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenFaceDz'];?></dd>
										<dt class="col-5 fs-2">གལུ་བྱུ་རུ་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenJwellWornDz'];?></dd>
										<dt class="col-5 fs-2">པད་ཁྲིའི་དབྱེ་བ</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenThroneDz'];?></dd>
										<dt class="col-5 fs-2">བཟོ་དབྱེ་བས་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenAppreanceDz'];?></dd>
										<dt class="col-5 fs-2">རྒྱབ་ཡོལ་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenBackRestDz'];?></dd>
										<dt class="col-5 fs-2">སྐུ་མདོང་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenColorDz'];?></dd>
										<dt class="col-5 fs-2">གཤམ་ཚད་སི་ཨེམ་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenShapeDz'];?></dd>
										<dt class="col-5 fs-2">སྐུའི་རིང་ཚད་སི་ཨེམ་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenSizeDz'];?></dd>
										<dt class="col-5 fs-2">གྲངས་ཁ་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenQtyDz'];?></dd>
										<dt class="col-5 fs-2">ལྗི་ཚད་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenWeightDz'];?></dd>
										<dt class="col-5 fs-2">གོང་ཚད་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenCostDz'];?></dd>
										<dt class="col-5 fs-2">ན་བཟའ་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenClothDz'];?></dd>
										<dt class="col-5 fs-2">དུས་རབས་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenAgeDz'];?></dd>
										<dt class="col-5 fs-2">འབྱུང་ཁུངས་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenSourceDz'];?></dd>
										<dt class="col-5 fs-2">ཚོན་གྱི་དབྱེ་བ་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenQualtyDz'];?></dd>
										<dt class="col-5 fs-2">ལོ་རྒྱུས་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenStoryDz'];?></dd>
										<dt class="col-5 fs-2">ངོས་འཛིན་</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenIdentificationDz'];?></dd>
									</dl>
								</div>
								<div class="card-header">
									<h3 class="card-title">Other details</h3>
								</div>
								<div class="card-body">
									<dl class="row">
										<dt class="col-5 fs-2">དཀོན་གཉེར་གྱི་མིང་རྟགས།</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenCaretakerDz'];?></dd>
										<dt class="col-5 fs-2">ཞིབ་དཔྱོད་པའི་མིང་རྟགས།</dt>
										<dd class="col-7 fs-2"><?php echo $row['TenCheckedByDz'];?></dd>
									</dl>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->						