<?php 
/**
 * View -- of Administration/LhakhangController/addlhakhangsection
 * chophel@athang.com
 */
$this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php echo $this->url('lhakhang', array('action' => 'addlhakhangsection','id'=>$page)); ?>"  enctype="multipart/form-data" >                  
    <div class="modal-header">
		<h4 class="modal-title"> <i class="icon ti ti-circle-plus"></i> <?php echo $this->title; ?></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">   
		<div class="row">
			<div class="form-group mb-3 col-lg-6">  
				<label class="form-label" for="GewogId">Gewog</label>
				<select id="GewogId" name="GewogId" class="form-select" data-placeholder="Select">
					<option value=""></option>
					<?php foreach($gewog as $gewogs):?>
						<option value="<?php echo $gewogs['id']?>">
							<?php echo $gewogs['GewogNameDz'];?></option>
					<?php endforeach;?>
				</select>
			</div>
			<div class="form-group mb-3 col-lg-6">  
				<label class="form-label" for="LhakhangId">Lhakhang</label>
				<select id="LhakhangId" name="LhakhangId" class="form-select" data-placeholder="Select">
					<option value=""></option>
				</select>
			</div>
			<div class="form-group mb-3 col-lg-6"> 
				<label class="form-label" for="SectionNameEn">Section Name(English)</label>
				<input type="text" class="form-control" name="SectionNameEn" id="SectionNameEn" placeholder="Section Name(English)" required /> 
			</div>
			<div class="form-group mb-3 col-lg-6"> 
				<label class="form-label" for="SectionNameDz">Section Name(Dzongkha)</label>
				<input type="text" class="form-control" name="SectionNameDz" id="SectionNameDz" placeholder="Section Name (Dzongkha)" /> 
			</div>
		</div>
		<div class="row">
			<div  class="form-group mb-3 col-lg-6">
				<label for="status" class="form-label">Status</label>
				<div>
					<label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="1" checked />
						<span class="form-check-label"> Yes </span>
					</label>
					<label class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="status" value="0" />
						<span class="form-check-label"> No </span>
					</label>
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="icon ti ti-check"></i>Save</button>
		<button type="button" class="btn btn-warning" data-bs-dismiss="modal"><i class="icon ti ti-x"></i>Cancel</button> 
    </div>
</form>
<script>
$(function(){
	$('select#GewogId').on('change', function(){
	$.post(
		 "<?php echo $this->url("lhakhang", array("action" => "getlhakhang")); ?>",
            {
                gewogId: $(this).val(),
            },
            function(data){
                $("select#LhakhangId").html(data.lhakhangValue);
                $('select#LhakhangId').trigger('chosen:updated');
            },
            'json'
        );
    });
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			GewogId: {
				validators: {
					notEmpty: {
						message: 'Please select Gewog.'
					}
				}
			},
			LhakhangId: {
				validators: {
					notEmpty: {
						message: 'Please select Lhakhang.'
					}
				}
			},
			SectionNameEn: {
				validators: {
					notEmpty: {
						message: 'Please provide Section Name.'
					}
				}
			},
			SectionNameDz: {
				validators: {
					notEmpty: {
						message: 'Please select Section Name.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap5: new FormValidation.plugins.Bootstrap5({
				rowSelector: '.mb-3',
			}),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>