<?php 
/**
 * View -- of Nangten/DebriController/editdebriAction
 * chophel@athang.com 
 */
	$this->headTitle($this->title);
?>
<?php foreach($debri as $row);?>
<div class="page-body">
	<div class="container-xl">
		<div class="row row-cards">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title"><i class="icon ti ti-user-plus"></i><?php echo $this->title;?></h3>
					</div>
					<form id="#form" method="post" action="<?php echo $this->url('debri', array('action' => 'editdebri','id'=>$row['id'])); ?>" enctype="multipart/form-data" >
						<div class="card-body">
						<h4 class="fs-2"><strong><i>དབྱེ་ཁག།</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
						<div class="row">
								<input type="hidden" name="debri_id" value="<?php echo $row['id'];?>">
								<div class="form-group mb-3 col-lg-6">
									<label for="category" class="form-label">དྲོན་སོ།</label>
									<div class="input-group mb-2">
										<select id="category" name="category" class="form-select" data-placeholder="Select">
											<?php foreach($category as $categorys):?>
												<option value="<?php echo $categorys['id']?>" <?php echo ($row['category']==$categorys['id'])?'selected':'';?>> 
													<?php echo $categorys['category'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
								<input type="hidden" name="statue_id" value="<?php echo $statues['id'];?>" >
								<div class="form-group mb-3 col-lg-6">
									<label for="subcategory" class="form-label">དཀོན་གཉེར་གྱི་མིང་རྟགས།</label>
									<div class="input-group mb-2">
										<select id="subcategory" name="subcategory" class="form-select" data-placeholder="Select">
											<?php foreach($subcategory as $subcategorys):?>
												<option value="<?php echo $subcategorys['id']?>" <?php echo ($row['subcategory']==$subcategorys['id'])?'selected':'';?>> 
													<?php echo $subcategorys['sub_category'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
							</div>
							<h4 class="fs-2"><strong><i>ལྷ་ཁང་ཁ་གསལ།</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label for="DzongkhagId" class="form-label">རྫོང་ཁག་</label>
									<div class="input-group mb-2">
										<select id="DzongkhagId" name="DzongkhagId" class="form-select" data-placeholder="Select">
											<?php foreach($dzongkhag as $dzongkhags):?>
												<option value="<?php echo $dzongkhags['id']?>" <?php echo ($row['DzongkhagId']==$dzongkhags['id'])?'selected':'';?>> 
													<?php echo $dzongkhags['DzongkhagNameDz'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="dob" class="form-label">རྒེད་འོག་:</label>
										<select id="GewogId" name="GewogId" class="form-select" data-placeholder="Select">
											<?php foreach($gewog as $gewogs):?>
												<option value="<?php echo $gewogs['id']?>" <?php echo ($row['GewogId']==$gewogs['id'])?'selected':'';?>> 
													<?php echo $gewogs['GewogNameDz'];?></option>
											<?php endforeach;?>
										</select>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="name" class="form-label">གཡུས་</label>
									<select id="VillageId" name="VillageId" class="form-select" data-placeholder="Select">
										<?php foreach($village as $villages):?>
											<option value="<?php echo $villages['id']?>" <?php echo ($row['VillageId']==$villages['id'])?'selected':'';?>> 
												<?php echo $villages['VillageNameDz'];?></option>
										<?php endforeach;?>
									</select>
								</div>
							</div>
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label for="LhakhangId" class="form-label">ལྷ་ཁང་གི་མིང་</label>
									<select id="LhakhangId" name="LhakhangId" class="form-select" data-placeholder="Select">
										<?php foreach($lhakhang as $lhakhangs):?>
											<option value="<?php echo $lhakhangs['id']?>" <?php echo ($row['LhakhangId']==$lhakhangs['id'])?'selected':'';?>> 
												<?php echo $lhakhangs['LhakhangNameDz'];?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="mobile" class="form-label">ནང་གསེས་</label>
									<select id="LhaSectionId" name="LhaSectionId" class="form-select" data-placeholder="Select">
										<?php foreach($section as $sections):?>
											<option value="<?php echo $sections['id']?>" <?php echo ($row['LhakhangId']==$sections['id'])?'selected':'';?>> 
												<?php echo $sections['SectionNameDz'];?></option>
										<?php endforeach;?>
									</select>
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaBuilderDz" class="form-label">བཞེངས་མི།</label>
									<input type="text" class="form-control" placeholder="བཞེངས་མི།" name="LhaBuilderDz" value="<?php echo $row['LhaBuilderDz'];?>" autocomplete="off" required >	
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaCenturyDz" class="form-label">དུས་རབས།</label>
									<input type="text" class="form-control" placeholder="དུས་རབས།" name="LhaCenturyDz" value="<?php echo $row['LhaCenturyDz'];?>" autocomplete="off" required >	
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaOwnerNameDz" class="form-label">བདག་དབང།</label>
									<input type="text" class="form-control" placeholder="བདག་དབང།" name="LhaOwnerNameDz" value="<?php echo $row['LhaOwnerNameDz'];?>" autocomplete="off" required >	
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaIdentificationNumber" class="form-label">དགུང་ཨང།</label>
									<input type="text" class="form-control" placeholder="དགུང་ཨང།" name="LhaIdentificationNumber" value="<?php echo $row['LhaIdentificationNumber'];?>" autocomplete="off" required >	
								</div>			
							</div>
							<h4 class="fs-2"><strong><i>དྲན་གསཽ།</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
							    <div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="role">ལྷ་ཚོགས།</label>
									<input type="text" class="form-control" placeholder="ལྷ་ཚོགས།" name="TenDescriptionDz" value="<?php echo $row['TenDescriptionDz'];?>" autocomplete="off" required >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenEastWestDz">ཕྱོགས།</label>
									<input type="text" class="form-control" placeholder="ཕྱོགས།" name="TenEastWestDz" value="<?php echo $row['TenEastWestDz'];?>" autocomplete="off" required >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenGoldScriptDz">གསེར་བྲིས།</label>
									<input type="text" class="form-control" placeholder="གསེར་བྲིས།" name="TenGoldScriptDz" value="<?php echo $row['TenGoldScriptDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenNoofDeitiesDz" class="form-label">ལྷ་ཚོགས་གྲངས།</label>
									<input type="text" class="form-control" placeholder="ལྷ་ཚོགས་གྲངས།" name=" TenNoofDeitiesDz" value="<?php echo $row['TenNoofDeitiesDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenTechniqueDz">བྲིས་གཞི།</label>
									<input type="text" class="form-control" placeholder="བྲིས་གཞི།" name="TenTechniqueDz" value="<?php echo $row['TenTechniqueDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenGroundDz" class="form-label">བྲིས་ཐངས།</label>
									<input type="text" class="form-control" placeholder="བྲིས་གཞི།" name="TenGroundDz" value="<?php echo $row['TenGroundDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenPainterDz">ལྷ་བྲིས་པ།</label>
									<input type="text" class="form-control" placeholder="ལྷ་བྲིས་པ།" name="TenPainterDz" value="<?php echo $row['TenPainterDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenQualtyDz">ཚོན་གྱི་དབྱེ་བ།</label>
									<input type="text" class="form-control" placeholder="ཚོན་གྱི་དབྱེ་བ།" name="TenQualtyDz" value="<?php echo $row['TenQualtyDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenSizeDz" class="form-label">ཚད།</label>
									<input type="text" class="form-control" placeholder="ཚད།" name="TenSizeDz" value="<?php echo $row['TenSizeDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenAgeDz" class="form-label">དུས་རབས།</label>
									<input type="text" class="form-control" placeholder="དུས་རབས།" name="TenAgeDz" value="<?php echo $row['TenAgeDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCurtainDz">ཡོལ་ལི།</label>
									<input type="text" class="form-control" placeholder="ཡོལ་ལི།" name="TenCurtainDz" value="<?php echo $row['TenCurtainDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenStoryDz">ལོ་རྒྱུས།</label>
									<input type="text" class="form-control" placeholder="ལོ་རྒྱུས།" name="TenStoryDz" value="<?php echo $row['TenCaretakerDz'];?>" autocomplete="off" >
								</div>
							</div>
							<h4 class="fs-2"><strong><i>ཁ་གསལ་གཞན།</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCaretakerDz">དཀོན་གཉེར་གྱི་མིང་རྟགས།</label>
									<input type="text" class="form-control" placeholder="དཀོན་གཉེར་གྱི་མིང་རྟགས།" name="TenCaretakerDz" value="<?php echo $row['TenCaretakerDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCheckedByDz">ཞིབ་དཔྱོད་པའི་མིང་རྟགས།</label>
									<input type="text" class="form-control" placeholder="ཞིབ་དཔྱོད་པའི་མིང་རྟགས།" name="TenCheckedByDz" value="<?php echo $row['TenCheckedByDz'];?>" autocomplete="off" >
								</div>
							</div>
						</div>
						<div class="card-footer">
							<button type="submit" class="btn btn-success"><span class="icon ti ti-check"></span> Save</button>
							<a class="btn btn-warning" onclick="javascript:history.back();"><span class="icon ti ti-x"></span> Cancel </a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function(){
	$('select#category').on('change', function(){
	$.post(
		 "<?php echo $this->url("debri", array("action" => "getsubcategory")); ?>",
            {
                categoryId: $(this).val(),
            },
            function(data){
                $("select#subcategory").html(data.subcategoryValue);
                $('select#subcategory').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#DzongkhagId').on('change', function(){
	$.post(
		 "<?php echo $this->url("debri", array("action" => "getgewog")); ?>",
            {
                dzongkhagId: $(this).val(),
            },
            function(data){
                $("select#GewogId").html(data.gewogValue);
                $('select#GewogId').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#GewogId').on('change', function(){
	$.post(
		 "<?php echo $this->url("debri", array("action" => "getvillage")); ?>",
            {
                gewogId: $(this).val(),
            },
            function(data){
                $("select#VillageId").html(data.villageValue);
                $('select#VillageId').trigger('chosen:updated');
				$("select#LhakhangId").html(data.lhakhangValue);
                $('select#LhakhangId').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#LhakhangId').on('change', function(){
	$.post(
		 "<?php echo $this->url("debri", array("action" => "getsection")); ?>",
            {
                lhaId: $(this).val(),
            },
            function(data){
                $("select#LhaSectionId").html(data.sectionValue);
                $('select#LhaSectionId').trigger('chosen:updated');
            },
            'json'
        );
    });
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				DzongkhagId: {
					validators: {
						notEmpty: {
							message: 'Please select dzongkhag.'
						},
					}
				},
				GewogId: {
					validators: {
						notEmpty: {
							message: 'Please select gewog.'
						},
					}
				},
				LhakhangId: {
					validators: {
						notEmpty: {
							message: 'Please select lhakhang.'
						},
					}
				},
				VillageId: {
					validators: {
						notEmpty: {
							message: 'Please select village'
						},
					}
				},
				LhaSectionId: {
					validators: {
						notEmpty: {
							message: 'Please select section.'
						}
					}
				},
				TenMakeId: {
					validators: {
						notEmpty: {
							message: 'Please select Msterial.'
						}
					}
				},
				TenCaretakerDz: {
					validators: {
						notEmpty: {
							message: 'Please provide care taker.'
						}
					}
				},
				TenCheckedByDz: {
					validators: {
						notEmpty: {
							message: 'Please provide Checker.'
						}
					}
				},
				category: {
					validators: {
						notEmpty: {
							message: 'Please select category.'
						}
					}
				},
				subcategory: {
					validators: {
						notEmpty: {
							message: 'Please select Sub category.'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap5: new FormValidation.plugins.Bootstrap5({
					rowSelector: '.mb-3',
				}),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
		$('form select').chosen().change(function () {
			fv.revalidateField($(this).attr('name'));
		});
	});
</script>