<?php 
/**
 * View -- of Nangten/NangtenController/statueAction
 * chophel@athang.com 
 */
	$this->headTitle($this->title);
?>
<?php foreach($statue as $statues);?>
<div class="page-body">
	<div class="container-xl">
		<div class="row row-cards">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title"><i class="icon ti ti-user-plus"></i><?php echo $this->title;?></h3>
					</div>
					<form id="#form" method="post" action="<?php echo $this->url('statue', array('action' =>'editstatue','id'=>$statues['id'])); ?>" enctype="multipart/form-data" >
					<div class="card-body">
						<h4><strong><i>Categorization</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
						 <div class="row">
								<div class="form-group mb-3 col-lg-6">
									<label for="category" class="form-label">Category</label>
									<div class="input-group mb-2">
										<select id="category" name="category" class="form-select" data-placeholder="Select">
											<?php foreach($category as $categorys):?>
												<option value="<?php echo $categorys['id']?>" <?php echo ($statues['category']==$categorys['id'])?'selected':'';?>> 
													<?php echo $categorys['category'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
								<input type="hidden" name="statue_id" value="<?php echo $statues['id'];?>" >
								<div class="form-group mb-3 col-lg-6">
									<label for="subcategory" class="form-label">Sub Category</label>
									<div class="input-group mb-2">
										<select id="subcategory" name="subcategory" class="form-select" data-placeholder="Select">
											<?php foreach($subcategory as $subcategorys):?>
												<option value="<?php echo $subcategorys['id']?>" <?php echo ($statues['subcategory']==$subcategorys['id'])?'selected':'';?>> 
													<?php echo $subcategorys['sub_category'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
							</div>
							<h4><strong><i>Lhakhang details</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label for="DzongkhagId" class="form-label">རྫོང་ཁག་</label>
									<div class="input-group mb-2">
										<select id="DzongkhagId" name="DzongkhagId" class="form-select" data-placeholder="Select">
											<?php foreach($dzongkhag as $dzongkhags):?>
												<option value="<?php echo $dzongkhags['id']?>" <?php echo ($statues['DzongkhagId']==$dzongkhags['id'])?'selected':'';?>> 
													<?php echo $dzongkhags['DzongkhagNameDz'];?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="dob" class="form-label">རྒེད་འོག་:</label>
										<select id="GewogId" name="GewogId" class="form-select" data-placeholder="Select">
											<?php foreach($gewog as $gewogs):?>
												<option value="<?php echo $gewogs['id']?>" <?php echo ($statues['GewogId']==$gewogs['id'])?'selected':'';?>> 
													<?php echo $gewogs['GewogNameDz'];?></option>
											<?php endforeach;?>
										</select>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="name" class="form-label">གཡུས་</label>
									<select id="VillageId" name="VillageId" class="form-select" data-placeholder="Select">
										<?php foreach($village as $villages):?>
											<option value="<?php echo $villages['id']?>" <?php echo ($statues['VillageId']==$villages['id'])?'selected':'';?>> 
												<?php echo $villages['VillageNameDz'];?></option>
										<?php endforeach;?>
									</select>
								</div>
							</div>
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label for="LhakhangId" class="form-label">ལྷ་ཁང་གི་མིང་</label>
									<select id="LhakhangId" name="LhakhangId" class="form-select" data-placeholder="Select">
										<?php foreach($lhakhang as $lhakhangs):?>
											<option value="<?php echo $lhakhangs['id']?>" <?php echo ($statues['LhakhangId']==$lhakhangs['id'])?'selected':'';?>> 
												<?php echo $lhakhangs['LhakhangNameDz'];?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="mobile" class="form-label">ནང་གསེས་</label>
									<select id="LhaSectionId" name="LhaSectionId" class="form-select" data-placeholder="Select">
										<?php foreach($section as $sections):?>
											<option value="<?php echo $sections['id']?>" <?php echo ($statues['LhakhangId']==$sections['id'])?'selected':'';?>> 
												<?php echo $sections['SectionNameDz'];?></option>
										<?php endforeach;?>
									</select>
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaBuilderDz" class="form-label">བཞེངས་མི</label>
									<input type="text" class="form-control" placeholder="LhaBuilderDz." name="LhaBuilderDz" value="<?php echo $statues['LhaBuilderDz'];?>" autocomplete="off" required >	
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaCenturyDz" class="form-label">དུས་རབས</label>
									<input type="text" class="form-control" placeholder="Century" name="LhaCenturyDz" value="<?php echo $statues['LhaCenturyDz'];?>" autocomplete="off" required >	
								</div>	
								<div class="form-group mb-3 col-lg-4">
									<label for="LhaOwnerNameDz" class="form-label">དབྱེ་བ་གཞན་</label>
									<input type="text" class="form-control" placeholder="Owner name" name="LhaOwnerNameDz" value="<?php echo $statues['LhaOwnerNameDz'];?>" autocomplete="off" required >	
								</div>		
							</div>
							<h4><strong><i>Nangten Details</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="role">མཚན་གསལ</label>
									<input type="text" class="form-control" placeholder="TenDescriptionDz" name="TenDescriptionDz" value="" autocomplete="off" required >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenMakeId" class="form-label">རྒྱུ</label>
									<select id="TenMakeId" name="TenMakeId" class="form-select" data-placeholder="Select">
										<?php foreach($material as $materials):?>
											<option value="<?php echo $materials['id']?>" <?php echo ($statues['TenMakeId']==$materials['id'])?'selected':'';?>> 
												<?php echo $materials['MaterialNameDz'];?></option>
										<?php endforeach;?>
									</select>
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenPostureDz">བཞུགས་ཚུལ་</label>
									<input type="text" class="form-control" placeholder="Posture" name="TenPostureDz" value="<?php echo $statues['TenPostureDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenTreasureDz" class="form-label">སྲོག་ཞུ་</label>
									<input type="text" class="form-control" placeholder="Treasure" name=" TenTreasureDz"value="<?php echo $statues['TenTreasureDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenForeHeadDz">བཛོད་སྤུར་</label>
									<input type="text" class="form-control" placeholder="ForeHead" name="TenForeHeadDz" value="<?php echo $statues['TenForeHeadDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenHandArticleDz" class="form-label">ཕྱག་མཚན་</label>
									<input type="text" class="form-control" placeholder="Hand Article" name="TenHandArticleDz" value="<?php echo $statues['TenHandArticleDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenFaceDz">ཞལ་དང་སྐུ་གཟུགས་ཀྱི་གསེར་</label>
									<input type="text" class="form-control" placeholder="Face" name="TenFaceDz" value="<?php echo $statues['TenFaceDz'];?>"autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenJwellWornDz">གལུ་བྱུ་རུ་</label>
									<input type="text" class="form-control" placeholder="Jwell Worn" name="TenJwellWornDz" value="<?php echo $statues['TenJwellWornDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenThroneDz" class="form-label">པད་ཁྲིའི་དབྱེ་བ</label>
									<input type="text" class="form-control" placeholder="Throne" name="TenThroneDz" value="<?php echo $statues['TenThroneDz'];?>"autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenAppreanceDz">བཟོ་དབྱེ་བས་</label>
									<input type="text" class="form-control" placeholder="Appreance" name="TenAppreanceDz" value="<?php echo $statues['TenAppreanceDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenBackRestDz" class="form-label">རྒྱབ་ཡོལ་</label>
									<input type="text" class="form-control" placeholder="Back Rest" name="TenBackRestDz" value="<?php echo $statues['TenBackRestDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenColorDz">སྐུ་མདོང་</label>
									<input type="text" class="form-control" placeholder="Color" name="TenColorDz" value="<?php echo $statues['TenColorDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenShapeDz">གཤམ་ཚད་སི་ཨེམ་</label>
									<input type="text" class="form-control" placeholder="Shape" name="TenShapeDz" value="<?php echo $statues['TenShapeDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenSizeDz">སྐུའི་རིང་ཚད་སི་ཨེམ་</label>
									<input type="text" class="form-control" placeholder="Size" name="TenSizeDz" value="<?php echo $statues['TenSizeDz'];?>" autocomplete="off"  >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenQtyDz">གྲངས་ཁ་</label>
									<input type="text" class="form-control" placeholder="Quantity" name="TenQtyDz" value="<?php echo $statues['TenQtyDz'];?>" autocomplete="off"  >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenWeighDz">ལྗི་ཚད་</label>
									<input type="text" class="form-control" placeholder="Weight" name="TenWeighDz" value="<?php echo $statues['TenWeighDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCostDz">གོང་ཚད་</label>
									<input type="text" class="form-control" placeholder="Cost" name="TenCostDz" value="<?php echo $statues['TenCostDz'];?>" autocomplete="off"  >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label for="TenClothDz" class="form-label">ན་བཟའ་</label>
									<input type="text" class="form-control" placeholder="Cloth" name="TenClothDz" value="<?php echo $statues['TenClothDz'];?>" autocomplete="off"  >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenAgeDz">དུས་རབས་</label>
									<input type="text" class="form-control" placeholder="Age" name="TenAgeDz" value="<?php echo $statues['TenAgeDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenSourceDz">འབྱུང་ཁུངས་</label>
									<input type="text" class="form-control" placeholder="Source" name="TenSourceDz" value="<?php echo $statues['TenSourceDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenQualtyDz">ཚོན་གྱི་དབྱེ་བ་</label>
									<input type="text" class="form-control" placeholder="Quality" name="TenQualtyDz" value="<?php echo $statues['TenQualtyDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenStoryDz">ལོ་རྒྱུས་</label>
									<input type="text" class="form-control" placeholder="Story" name="TenStoryDz" value="<?php echo $statues['TenStoryDz'];?>"" autocomplete="off" >
								</div>
								
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenIdentificationDz">ངོས་འཛིན་</label>
									<input type="text" class="form-control" placeholder="Identification" name="TenIdentificationDz" value="<?php echo $statues['TenIdentificationDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenRemarkDz">དྲོན་སོ།</label>
									<input type="text" class="form-control" placeholder="Remark" name="TenRemarkDz" value="<?php echo $statues['TenRemarkDz'];?>" autocomplete="off" >
								</div>
							</div>
							<h4><strong><i>Other details</i></strong></h4> <hr style="border-top:1px solid #c1bdbd;margin-top:10px;margin-bottom:10px;">
							<div class="row">
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCaretakerDz">དཀོན་གཉེར་གྱི་མིང་རྟགས།</label>
									<input type="text" class="form-control" placeholder="TenCaretakerDz" name="TenCaretakerDz" value="<?php echo $statues['TenCaretakerDz'];?>" autocomplete="off" >
								</div>
								<div class="form-group mb-3 col-lg-4">
								</div>
								<div class="form-group mb-3 col-lg-4">
									<label class="form-label" for="TenCheckedByDz">ཞིབ་དཔྱོད་པའི་མིང་རྟགས།</label>
									<input type="text" class="form-control" placeholder="TenCheckedByDz" name="TenCheckedByDz" value="<?php echo $statues['TenCheckedByDz'];?>" autocomplete="off" >
								</div>
							</div>
						</div>
						<div class="card-footer">
							<button type="submit" class="btn btn-success"><span class="icon ti ti-check"></span> Save</button>
							<a class="btn btn-warning" onclick="javascript:history.back();"><span class="icon ti ti-x"></span> Cancel </a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function(){
	$('select#category').on('change', function(){
	$.post(
		 "<?php echo $this->url("statue", array("action" => "getsubcategory")); ?>",
            {
                categoryId: $(this).val(),
            },
            function(data){
                $("select#subcategory").html(data.subcategoryValue);
                $('select#subcategory').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#DzongkhagId').on('change', function(){
	$.post(
		 "<?php echo $this->url("statue", array("action" => "getgewog")); ?>",
            {
                dzongkhagId: $(this).val(),
            },
            function(data){
                $("select#GewogId").html(data.gewogValue);
                $('select#GewogId').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#GewogId').on('change', function(){
	$.post(
		 "<?php echo $this->url("statue", array("action" => "getvillage")); ?>",
            {
                gewogId: $(this).val(),
            },
            function(data){
                $("select#VillageId").html(data.villageValue);
                $('select#VillageId').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#GewogId').on('change', function(){
	$.post(
		 "<?php echo $this->url("statue", array("action" => "getvillage")); ?>",
            {
                gewogId: $(this).val(),
            },
            function(data){
                $("select#VillageId").html(data.villageValue);
                $('select#VillageId').trigger('chosen:updated');
            },
            'json'
        );
    });
	$('select#GewogId').on('change', function(){
	$.post(
		 "<?php echo $this->url("statue", array("action" => "getvillage")); ?>",
            {
                gewogId: $(this).val(),
            },
            function(data){
                $("select#LhakhangId").html(data.lhakhangValue);
                $('select#LhakhangId').trigger('chosen:updated');
            },
            'json'
        );
    });
	/*$('select#LhakhangId').on('change', function(){
	$.post(
		 "<?php //echo $this->url("nangten", array("action" => "getsection")); ?>",
            {
                lhaId: $(this).val(),
            },
            function(data){
                $("select#LhaSectionId").html(data.sectionValue);
                $('select#LhaSectionId').trigger('chosen:updated');
            },
            'json'
        );
    });*/
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				DzongkhagId: {
					validators: {
						notEmpty: {
							message: 'Please select dzongkhag.'
						},
					}
				},
				GewogId: {
					validators: {
						notEmpty: {
							message: 'Please select gewog.'
						},
					}
				},
				LhakhangId: {
					validators: {
						notEmpty: {
							message: 'Please select lhakhang.'
						},
					}
				},
				VillageId: {
					validators: {
						notEmpty: {
							message: 'Please select village'
						},
					}
				},
				LhaSectionId: {
					validators: {
						notEmpty: {
							message: 'Please select section.'
						}
					}
				},
				TenMakeId: {
					validators: {
						notEmpty: {
							message: 'Please select Msterial.'
						}
					}
				},
				TenCaretakerDz: {
					validators: {
						notEmpty: {
							message: 'Please provide care taker.'
						}
					}
				},
				TenCheckedByDz: {
					validators: {
						notEmpty: {
							message: 'Please provide Checker.'
						}
					}
				},
				category: {
					validators: {
						notEmpty: {
							message: 'Please select category.'
						}
					}
				},
				subcategory: {
					validators: {
						notEmpty: {
							message: 'Please select Sub category.'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap5: new FormValidation.plugins.Bootstrap5({
					rowSelector: '.mb-3',
				}),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
		$('form select').chosen().change(function () {
			fv.revalidateField($(this).attr('name'));
		});
		picker.on('selected', function (e) {
			fv.revalidateField(picker.options.element.name);
		});
	});
	$('#uploadfile').ace_file_input({
			no_file:'No File ...',
			btn_choose:'Choose',
			btn_change:'Change',
			droppable:false,
			onchange:null,
			thumbnail: 'small',
			whitelist:'doc|docx|pdf|jpg',
			//blacklist:'exe|php'
			//onchange:''
		}); 
</script>