<?php 
/**
 * View -- of Administration/UserController/viewAction
 * chophel@athang.com 
 */
	$this->headTitle($this->title);
?>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<div id="modal01" class="w3-modal" onclick="this.style.display='none'">
  <span class="w3-button w3-hover-red w3-xlarge w3-display-topright">&times;</span>
  <div class="w3-modal-content w3-animate-zoom">
    <img id="img01" style="width:100%">
  </div>
</div>

<?php foreach($statue as $row);?>
<div class="page-body">
	<div class="container-xl">
		<div class="row row-cards">
			<div class="col-12">
				<div class="card" id="print-content">
					<div class="card-header">
						<div class="col-2">
							<?php echo $this->button(3,$row['id']);?>
						</div>
						<div class="col-2">
							<?php echo $this->button(6,$row['id'],'','236');?>
						</div>
						<div class="col-2">
							<?php echo $this->button(6,$row['id'],'','235');?>
						</div>
						<div class="col-auto ms-auto d-print-none">
						<div class="btn-list">
							<span data-bs-toggle='tooltip' data-bs-placement='top' title='PDF Print'>
								<a class='btn btn-light btn-sm' id="print">
								<i class="icon ti ti-printer"></i>PDF</a></span>
						</div>
				 	</div>
					</div>
					<div class="row row-cards">
					<div class="container">
						<div class="card">
							<div class="row align-items-start">
								<table class="table card-table table-vcenter text-nowrap datatable" id="dataTables">
									<tbody>
										<tr>
											<td></td>
											<td></td>
											<td></td>
											<td></td>
											<td></td>
											<td><span class="avatar avatar-xl" style="background-image: url(<?php echo $this->basePath() . '/images/druk.jfif';?>)"></span></td>
											<td><h1>ཅ་རྙིང་འཛིན་སྐྱོང་སྡེ་ཚན།</h1>
												<h2>སྲོལ་འཛིན་ལས་ཁུངས།</h2>
												<h3>སྐུ་རྟེན།</h3>
											</td>
											<td>
												<img class="avatar avatar-xl img-thumbnail" src="<?php echo $this->basePath()."/upload/statue/".$row['TenImage'];?>" onclick="onClick(this)" class="w3-hover-opacity">
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
						</div>
						<div class="col-lg-4">
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<table class="table card-table table-vcenter text-nowrap datatable" id="dataTables">
											<tdead>
												<tr>
													<td></td>
												</tr>
											</tdead>
											<tbody>
												<tr>
													<td class="fw-bold fs-2">རྫོང་ཁག་:</td>
													<td class="fs-2"><?php echo $row['DzongkhagNameDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">རྒེད་འོག་:</td>
													<td class="fs-2"><?php echo $row['GewogNameDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">གཡུས་:</td>
													<td class="fs-2"><?php echo $row['VillageDz'];?></td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
						 	</div>
						</div>
						<div class="col-lg-4">
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<table class="table card-table table-vcenter text-nowrap datatable" id="dataTables">
											<tdead>
												<tr>
													<td></td>
												</tr>
											</tdead>
											<tbody>
												<tr>
													<td class="fw-bold fs-2">ལྷ་ཁང་གི་མིང་:</td>
													<td class="fs-2"><?php echo $row['LhakhangNameDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">གསེས་:</td>
													<td class="fs-2"><?php echo $row['LhaSectionNameDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">བཞེངས་མི:</td>
													<td class="fs-2"><?php echo $row['LhaBuilderDz'];?></td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
						 	</div>
						</div>
						<div class="col-lg-4">
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<table class="table card-table table-vcenter text-nowrap datatable" id="dataTables">
											<tdead>
												<tr>
													<td></td>
												</tr>
											</tdead>
											<tbody>
												<tr>
													<td class="fw-bold fs-2">དུས་རབས:</td>
													<td class="fs-2"><?php echo $row['LhaCenturyDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">དབྱེ་བ་གཞན་:</td>
													<td class="fs-2"><?php echo $row['LhaOwnerNameDz'];?></td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
						 	</div>
						</div>
						<div class="col-lg-6">
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<table class="table card-table table-vcenter text-nowrap datatable" id="dataTables">
											<tdead>
												<tr>
													<td></td>
												</tr>
											</tdead>
											<tbody>
												<tr>
													<td class="fw-bold fs-2">མཚན་གསལ:</td>
													<td class=" fs-2"><?php echo $row['TenDescriptionDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">རྒྱུ</td>
													<td class=" fs-2"><?php echo $row['TenMaterialDz'];?></td>
												</tr>
												<tr>	
													<td class="fw-bold fs-2">བཞུགས་ཚུལ་</td>
													<td class=" fs-2"><?php echo $row['TenPostureDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">སྲོག་ཞུ་</td>
													<td class=" fs-2"><?php echo $row['TenTreasureDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">བཛོད་སྤུར་</td>
													<td class=" fs-2"><?php echo $row['TenForeHeadDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">ཕྱག་མཚན་</td>
													<td class=" fs-2"><?php echo $row['TenForeHeadDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">ཞལ་དང་སྐུ་གཟུགས་ཀྱི་གསེར་</td>
													<td class=" fs-2"><?php echo $row['TenFaceDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">གལུ་བྱུ་རུ་</td>
													<td class=" fs-2"><?php echo $row['TenJwellWornDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">པད་ཁྲིའི་དབྱེ་བ</td>
													<td class=" fs-2"><?php echo $row['TenThroneDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">བཟོ་དབྱེ་བས་</td>
													<td class=" fs-2"><?php echo $row['TenAppreanceDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">རྒྱབ་ཡོལ་</td>
													<td class=" fs-2"><?php echo $row['TenBackRestDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">སྐུ་མདོང་</td>
													<td class=" fs-2"><?php echo $row['TenColorDz'];?></td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
						 	</div>
						</div>
						<div class="col-lg-6">
							<div class="card">
								<div class="card-body">
								<div class="table-responsive">
										<table class="table card-table table-vcenter text-nowrap datatable" id="dataTables">
											<tdead>
												<tr>
													<td></td>
												</tr>
											</tdead>
											<tbody>
												<tr>
													<td class="fw-bold fs-2">གཤམ་ཚད་སི་ཨེམ་</td>
													<td class=" fs-2"><?php echo $row['TenShapeDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">སྐུའི་རིང་ཚད་སི་ཨེམ་</td>
													<td class=" fs-2"><?php echo $row['TenSizeDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">གྲངས་ཁ་</td>
													<td class=" fs-2"><?php echo $row['TenQtyDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">ལྗི་ཚད་</td>
													<td class=" fs-2"><?php echo $row['TenWeightDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">གོང་ཚད་</td>
													<td class=" fs-2"><?php echo $row['TenCostDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">ན་བཟའ་</td>
													<td class=" fs-2"><?php echo $row['TenClothDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">དུས་རབས་</td>
													<td class=" fs-2"><?php echo $row['TenAgeDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">འབྱུང་ཁུངས་</td>
													<td class=" fs-2"><?php echo $row['TenSourceDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">ཚོན་གྱི་དབྱེ་བ་</td>
													<td class=" fs-2"><?php echo $row['TenQualtyDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">ལོ་རྒྱུས་</td>
													<td class=" fs-2"><?php echo $row['TenStoryDz'];?></td>
												</tr>
												<tr>
													<td class="fw-bold fs-2">ངོས་འཛིན་</td>
													<td class=" fs-2"><?php echo $row['TenIdentificationDz'];?></td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
								
							</div>
						</div>
						<div class="col-lg-12">
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<table class="table card-table table-vcenter text-nowrap datatable" id="dataTables">
											<tdead>
												<tr>
													<td class="fw-bold fs-2">དཀོན་གཉེར་གྱི་མིང་རྟགས།:</td>
													<td class="fw-bold fs-2">ཞིབ་དཔྱོད་པའི་མིང་རྟགས།:</td>
												</tr>
											</tdead>
											<tbody>
												<tr>
													<td class=" fs-2"><?php echo $row['TenCaretakerDz'];?></td>
													<td class=" fs-2"><?php echo $row['TenCheckedByDz'];?></td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
						 	</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->		
<script>
$('document').ready(function(){
	$('#print').gentcpdf({
		content: '#print-content',
		src:"<?php echo $this->url('print', array('action' => 'index'));?>",
		orentation:"P",
		size: 'A4',
	});  
	var title_table = "<?php echo $this->title;?>";
	$('#dataTables').DataTable( {
		dom: 'Bfrtip',
		columnDefs: [ {
			visible: falses
		} ],
		"paging":   false,
		"ordering": false,
		"info":     false,
		
	});
});
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
}
</script>
